apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: wms
type: Opaque
stringData:
  postgres-password: "postgres"
  organization-db-user: "postgres"
  organization-db-password: "postgres"
  product-db-user: "postgres"
  product-db-password: "postgres"
  warehouse-db-user: "postgres"
  warehouse-db-password: "postgres"
  sso-db-user: "postgres"
  sso-db-password: "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: wms
type: Opaque
stringData:
  redis-password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: wms
type: Opaque
stringData:
  rabbitmq-password: "rabbitmq"

